branches:
  only:
    - "master"
language: generic
matrix:
  include:
    - os: linux
      before_install:
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - wget -q https://swift.org/builds/swift-4.0-branch/ubuntu1404/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-09-08-a/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-09-08-a-ubuntu14.04.tar.gz
        - tar xzf swift-4.0-DEVELOPMENT-SNAPSHOT-2017-09-08-a-ubuntu14.04.tar.gz
        - export PATH=${PWD}/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-09-08-a-ubuntu14.04/usr/bin:"${PATH}"
      script:
        - swift build
        - .build/debug/autobahn drive buildRelease
        - .build/debug/autobahn drive test
    - os: osx
      osx_image: xcode9
      sudo: required
      script:
        - swift build
        - .build/debug/autobahn drive buildRelease
        - .build/debug/autobahn drive test
